# Generated by Django 3.2.8 on 2021-11-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default=None)),
                ('author', models.CharField(default='Admin', max_length=150)),
            ],
        ),
    ]
